# our base image
FROM php:7.1-fpm

ENV PHP_REDIS_VERSION 3.1.4

#install zip extension for composer
RUN apt-get update && apt-get install -y \
    zip \
    git \
    && docker-php-ext-install posix \
    && docker-php-ext-install pcntl \
    && docker-php-ext-configure pcntl --enable-pcntl

#install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN chown -R www-data:www-data /var/www

WORKDIR  /var/www/golos-event-listener